[build]
  command = "curl -sSv --max-time 20 https://story.smarthr-ui.dev/index.json -o /dev/null; curl -sS4 -o /dev/null -w 'ipv4:%{http_code}\\n' https://story.smarthr-ui.dev/index.json; pnpm run build:prod"
  publish = "dist"
[dev]
  command = 'pnpm run dev'
  targetPort = 8000
  port = 8888
  publish = 'dist'

