import fs from 'node:fs';
import { createRequire } from 'node:module';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const require = createRequire(import.meta.url);

const CONTENT_DIR = path.join(__dirname, '../src/content/articles');

interface CodeBlock {
  code: string;
  lineNumber: number;
  withStyled: boolean;
}

interface FileData {
  blocks: CodeBlock[];
  imports: string[];
}

/**
 * MDXファイルからimport文を抽出
 */
function extractImports(content: string): string[] {
  const lines = content.split('\n');
  const imports: string[] = [];

  for (const line of lines) {
    // frontmatter の終了後からコンテンツまで
    if (line.startsWith('import ') && line.includes('from')) {
      // smarthr-ui からのimportのみを抽出
      if (line.includes("from 'smarthr-ui'") || line.includes('from "smarthr-ui"')) {
        imports.push(line);
      }
    }
  }

  return imports;
}

/**
 * MDXファイルから `tsx editable` コードブロックを抽出
 */
function extractEditableCodeBlocks(filePath: string): FileData {
  const content = fs.readFileSync(filePath, 'utf-8');
  const lines = content.split('\n');
  const blocks: CodeBlock[] = [];
  const imports = extractImports(content);

  let inCodeBlock = false;
  let isEditableBlock = false;
  let currentBlock: string[] = [];
  let blockStartLine = 0;

  let currentBlockWithStyled = false;

  for (let i = 0; i < lines.length; i++) {
    const line = lines[i];
    const lineNumber = i + 1;

    // コードブロックの開始を検出
    if (line.startsWith('```tsx editable')) {
      inCodeBlock = true;
      isEditableBlock = true;
      currentBlock = [];
      blockStartLine = lineNumber;
      currentBlockWithStyled = line.includes('withStyled');
      continue;
    }

    // コードブロックの終了を検出
    if (line.startsWith('```') && inCodeBlock) {
      if (isEditableBlock && currentBlock.length > 0) {
        blocks.push({
          code: currentBlock.join('\n'),
          lineNumber: blockStartLine,
          withStyled: currentBlockWithStyled,
        });
      }
      inCodeBlock = false;
      isEditableBlock = false;
      currentBlock = [];
      currentBlockWithStyled = false;
      continue;
    }

    // コードブロック内の行を収集
    if (inCodeBlock && isEditableBlock) {
      currentBlock.push(line);
    }
  }

  return { blocks, imports };
}

/**
 * 全MDXファイルを走査してコードブロックを抽出
 */
function processAllMdxFiles(dir: string): Map<string, FileData> {
  const result = new Map<string, FileData>();

  function walkDir(currentDir: string) {
    const entries = fs.readdirSync(currentDir, { withFileTypes: true });

    for (const entry of entries) {
      const fullPath = path.join(currentDir, entry.name);

      if (entry.isDirectory()) {
        walkDir(fullPath);
      } else if (entry.isFile() && entry.name.endsWith('.mdx')) {
        const fileData = extractEditableCodeBlocks(fullPath);
        if (fileData.blocks.length > 0) {
          const dirPath = path.dirname(fullPath);
          result.set(dirPath, fileData);
        }
      }
    }
  }

  walkDir(dir);
  return result;
}

/**
 * smarthr-uiから全エクスポートを取得
 */
function getAllSmarthrUIExports(): string[] {
  try {
    const smarthrUI = require('smarthr-ui');
    return Object.keys(smarthrUI).sort();
  } catch (error) {
    console.warn('Failed to load smarthr-ui exports, using fallback list');
    return [];
  }
}

/**
 * TypeScriptファイルを生成
 */
function generateTypeScriptFile(blocks: CodeBlock[], mdxImports: string[]): string {
  // smarthr-uiから全エクスポートを取得
  const allSmarthrUIExports = getAllSmarthrUIExports();

  const baseImports = `/** *
* DO NOT EDIT THIS FILE MANUALLY.
*
* This file is auto-generated from MDX files in the content directory.
* Please edit the original MDX files instead of this one.
* Each code block is exported as a React component named L{lineNumber}, where {lineNumber} is the line number of the code block in the original MDX file.
* **/
import React from 'react';
import styled, { css } from 'styled-components';
import {
  ${allSmarthrUIExports.join(', ')}
} from 'smarthr-ui';

// This file is auto-generated by scripts/extract-editable-code.ts
// Do not edit manually

`;

  // MDXからのimportを含める（ただし重複を避けるため、smarthr-uiからのimportは削除）
  const filteredMdxImports = mdxImports.filter((imp) => !imp.includes("from 'smarthr-ui'") && !imp.includes('from "smarthr-ui"'));
  const mdxImportsStr = filteredMdxImports.length > 0 ? filteredMdxImports.join('\n') + '\n\n' : '';

  const imports = baseImports + mdxImportsStr;

  const exports = blocks
    .map(({ code, lineNumber, withStyled }) => {
      if (withStyled) {
        // withStyled の場合は、render()の引数部分だけを抽出して返す
        const lines = code.split('\n');
        const renderIndex = lines.findIndex((line) => line.trim().startsWith('render('));

        if (renderIndex >= 0) {
          // render() より前の部分（styled定義など）
          const beforeRender = lines.slice(0, renderIndex).join('\n');
          // render() の引数部分
          const afterRender = lines.slice(renderIndex).join('\n');
          // render( と末尾の ) を削除
          const renderContent = afterRender.replace(/^\s*render\s*\(\s*\n?/, '').replace(/\)\s*$/, '');

          return `export const L${lineNumber} = () => {
${beforeRender
  .split('\n')
  .map((line) => `  ${line}`)
  .join('\n')}

  return (
${renderContent
  .split('\n')
  .map((line) => `    ${line}`)
  .join('\n')}
  );
};`;
        } else {
          // render() がない場合はそのまま関数化
          return `export const L${lineNumber} = () => {
${code
  .split('\n')
  .map((line) => `  ${line}`)
  .join('\n')}
};`;
        }
      } else {
        // 通常の場合は関数としてラップ
        return `export const L${lineNumber} = () => {
  return (
${code
  .split('\n')
  .map((line) => `    ${line}`)
  .join('\n')}
  );
};`;
      }
    })
    .join('\n\n');

  return imports + exports;
}

/**
 * メイン処理
 */
function main() {
  console.log('Extracting editable code blocks from MDX files...');

  const fileMap = processAllMdxFiles(CONTENT_DIR);

  let totalBlocks = 0;
  for (const [dirPath, fileData] of fileMap.entries()) {
    const checkDir = path.join(dirPath, '_check');

    // _check ディレクトリを作成
    if (!fs.existsSync(checkDir)) {
      fs.mkdirSync(checkDir, { recursive: true });
    }

    // index.tsx を生成
    const tsContent = generateTypeScriptFile(fileData.blocks, fileData.imports);
    const outputPath = path.join(checkDir, 'index.tsx');
    fs.writeFileSync(outputPath, tsContent, 'utf-8');

    totalBlocks += fileData.blocks.length;
    console.log(`  ✓ ${path.relative(CONTENT_DIR, dirPath)}: ${fileData.blocks.length} block(s)`);
  }

  console.log(`\nTotal: ${totalBlocks} editable code blocks extracted to ${fileMap.size} directories`);
}

main();
