name: lint

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

env:
  NPM_CONFIG_IGNORE_SCRIPTS: 'true'
  NPM_CONFIG_BEFORE: ''
  PNPM_CONFIG_MINIMUM_RELEASE_AGE: '1' # days

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set NPM_CONFIG_BEFORE
        run: |
          echo "NPM_CONFIG_BEFORE=$(date -u -d '24 hours ago' +%Y-%m-%dT%H:%M:%SZ)" >> "$GITHUB_ENV"

      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0

      - name: Setup pnpm
        uses: pnpm/action-setup@0977fd99725f1db4007ccb2928dbb4e90d06cc86 # v6.0.10

      - name: Setup Node.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version-file: '.node-version'
          cache: 'pnpm'

      - run: pnpm install --frozen-lockfile
      - run: pnpm lint
